server:
  port: 9009

spring:
  application:
    name: qingyin-gateway
  main:
    # gateway组件中的 spring-boot-starter-webflux 和
    # springboot作为web项目启动必不可少的 spring-boot-starter-web 出现冲突。
    # 直接排除
    web-application-type: reactive
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。

  cloud:
    nacos:
      discovery:
        enabled: true
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: 2636c16a-f8a7-48c5-974c-7a712fc0db95

  # Redis配置
  redis:
    host: localhost   # Redis服务地址
    port: 6379        # Redis端口
    password: 123456  # Redis密码
    database: 0       # 数据库索引
    timeout: 5000     # 连接超时
    lettuce:
      pool:
        max-wait: 30000 # 连接池最大阻塞等待时间(使用负数表示没有限制,默认-1)
        max-active: 100 # 连接池最大连接数(使用负数表示没有限制,默认8)
        max-idle: 20    # 连接池中的最大空闲连接(默认8)
        min-idle: 0     # 连接池中的最小空闲连接(默认0)

#  kafka:
#    bootstrap-servers: 192.168.31.118:9092
#    producer:
#      retries: 3
#    consumer:
#      auto-offset-reset: latest
#  zipkin:
#    sender:
#      type: kafka # 默认是 web
#    base-url: http://192.168.31.118:9411/


    # 静态路由
  #    gateway:
  #      routes:
  #        - id: path_route # 路由的ID
  #          uri: 127.0.0.1:8080/user/{id} # 匹配后路由地址
  #          predicates: # 断言, 路径相匹配的进行路由
  #            - Path=/user/{id}


# 这个地方独立配置, 是网关的数据, 代码 GatewayConfig.java 中读取被监听
nacos:
  gateway:
    route:
      config:
        data-id: qingyin-gateway-router
        group: qingyin

# 忽略校验路径
validate:
  skips:
    paths:
      - '/qingyin-rpc-api/authority/register'
      - '/qingyin-rpc-api/authority/token'


feign:
  # 不使用httpclient，改用okhttp
  httpclient:
    enabled: false
  okhttp:
    enabled: true
    # 是否禁用重定向
    follow-redirects: true
    connect-timeout: 5000
    # 链接失败是否重试
    retry-on-connection-failure: true
    read-timeout: 5000
    write-timeout: 5000
    # 最大空闲数量
    max-idle-connections: 5
    # 生存时间
    keep-alive-duration: 15000

  # 开启压缩功能
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
