spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: 2636c16a-f8a7-48c5-974c-7a712fc0db95
        
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.31.5
                port: 5672
                username: admin
                password: 123456
                virtual-host: my_vhost

  # 数据源配置
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      # 数据源
      dynamic:
        primary: qingyin-account-db
        strict: false
        datasource:
          qingyin-account-db:
            url: jdbc:mysql://localhost:3306/qingyin-account?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
            driver-class-name: com.mysql.jdbc.Driver # MySql的驱动
            username: root # 数据库账号
            password: 123456 # 数据库密码