version: "3.8"
services:


  jenkins:
    image: jenkins/jenkins:2.440.2
    #restart: always
    networks:
      - tool_net
    privileged: true
    container_name: jenkins
    ports:
      - 8000:8080
      - 50000:50000
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/data/jenkins:/var/jenkins_home
      # 传入maven包jdk包
      - /www/wwwroot/apache-maven-3.6.3:/usr/local/maven
      - /opt/java/jdk1.8.0_381:/usr/local/java
      - /usr/bin/git:/usr/local/git
      # 在容器中使用宿主机的docker
      - /usr/bin/docker:/usr/bin/docker
      # 注意要在jenkins容器中开放权限
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai


  nacos:
    # restart: always
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/nacos-server:2.2.0
    container_name: nacos
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849

    privileged: true
    # depends_on:
    #   - mysql
    networks:
      - tool_net
    environment:
      # 集群配置
      # MODE: cluster
      # NACOS_SERVERS: nacos-server01:8848 nacos-server02:8848 nacos-server03:8848

      # 单机
      MODE: standalone

      # 副本
      NACOS_REPLICAS: 1
      PREFER_HOST_MODE: hostname

      # 个人安全配置
      NACOS_AUTH_ENABLE: "true"
      NACOS_AUTH_TOKEN_EXPIRE_SECONDS: 18000
      NACOS_AUTH_TOKEN: NStQdHM3WCU3RVYlMjRZdG04aUolMkM3JTJDQnhyUCU1RXFMJTIxaiUyOCUyM1JZ
      NACOS_AUTH_IDENTITY_KEY: tianji
      NACOS_AUTH_IDENTITY_VALUE: tianji

      # 账号密码
      NACOS_AUTH_SYSTEM_TYPE: nacos

      # 虚拟机设置
      JVM_XMS: 128m
      JVM_XMX: 128m
      JVM_MS: 64m
      JVM_MMS: 64m

      # 存储
      SPRING_DATASOURCE_PLATFORM: mysql
      # 注：这里不能为`127.0.0.1`或`localhost`方式！！！
      MYSQL_SERVICE_HOST: 121.40.248.33
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: nacos_config
      MYSQL_SERVICE_PASSWORD: 4PcnFCtKenamcANf
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useSSL=false
    volumes:
      - /www/wwwroot/data/nacos/logs:/home/nacos/logs
      - /www/wwwroot/data/nacos/init.d:/home/nacos/init.d
      - /www/wwwroot/data/nacos/data:/home/nacos/data

  kafka1:
    container_name: kafka01
    image: 'bitnami/kafka'
    user: root
    networks:
      - kafka_net
    ports:
      - '19092:9092'
      - '19093:9093'
    environment:
      # 允许使用Kraft
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 定义kafka服务端socket监听端口（Docker内部的ip地址和端口）
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      #定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.31.128:19092
      # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
      - KAFKA_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=1
      - KAFKA_CFG_NODE_ID=1
       # 集群地址
      # - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka11:9093,2@kafka22:9093,3@kafka33:9093
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka01:9093
      # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 设置broker最大内存，和初始内存
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
    volumes:
      - /www/wwwroot/data/kafka/broker:/bitnami/kafka:rw
    
  # https://blog.csdn.net/Vector97/article/details/128539970
  kafkaui:
    container_name: kafkaui
    image: provectuslabs/kafka-ui:latest
    networks:
      - kafka_net
    ports:
      - '8050:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka01
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka01:9092
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - SERVER_SERVLET_CONTEXT_PATH=/
      - AUTH_TYPE=LOGIN_FORM
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin123

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - /home/docker/rabbitmq/data/:/var/lib/rabbitmq/
      - /home/docker/rabbitmq/log/:/var/log/rabbitmq/log/
      - /home/docker/rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /home/docker/rabbitmq/config/10-default-guest-user.conf:/etc/rabbitmq/conf.d/10-default-guest-user.conf
      - /home/docker/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.9.0.ez:/opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.9.0.ez
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8

  skywalking-oap:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/skywalking-oap-server:9.5.0
    container_name: skywalking-oap
    privileged: true
    networks:
      - skywalking
      - es_net
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: es:9200
      SW_ES_USER: elastic
      SW_ES_PASSWORD: elastic123
      TZ: Asia/Shanghai

  skywalking-ui:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/skywalking-ui:9.5.0
    container_name: skywalking-ui
    privileged: true
    networks:
      - skywalking
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap:oap
    ports:
      - 8049:8080
    environment:
      SW_OAP_ADDRESS: http://oap:12800
      TZ: Asia/Shanghai
  
  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/elasticsearch:7.14.1
    container_name: elasticsearch
    networks:
      - es_net
    # restart: always
    ports:
      - 9200:9200
      - 9300:9300
    privileged: true
    volumes:
      - /www/wwwroot/data/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /www/wwwroot/data/es/logs:/usr/share/elasticsearch/logs
      - /www/wwwroot/data/es/data:/usr/share/elasticsearch/data
      - /www/wwwroot/data/es/plugins:/usr/share/elasticsearch/plugins
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - LANG=en_US.UTF-8

  kibana:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/kibana:7.14.1
    container_name: kibana
    privileged: true
    networks:
      - es_net
    # restart: always
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    volumes:
      - /www/wwwroot/data/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_URL=http://es:9200
      - TZ=Asia/Shanghai

  xxljob:
    image: xuxueli/xxl-job-admin:2.4.1
    container_name: xxljob
    privileged: true
    ports:
      - 9003:8080
    volumes:
      - /www/wwwroot/data/xxl-job/logs:/data/applogs
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
                   --spring.datasource.username=root
                   --spring.datasource.password=123456
                   --server.servlet.context-path=/xxl-job-admin
                   --spring.mail.host=smtp.qq.com
                   --spring.mail.port=25
                   --spring.mail.username=xxx@qq.com
                   --spring.mail.from=xxx@qq.com
                   --spring.mail.password=xxx
                   --xxl.job.accessToken="

networks:
  tool_net:
    driver: bridge
  kafka_net:
    driver: bridge
  es_net:
    driver: bridge
  skywalking:
    driver: bridge