server:
  port: 8077

spring:

  cloud:
    nacos:
      discovery:
        enabled: true
        username: nacos
        password: nacos
        server-addr: 121.40.248.33:8848
        namespace: 2636c16a-f8a7-48c5-974c-7a712fc0db95

  kafka:
    bootstrap-servers: 192.168.31.128:9092
    producer:
      retries: 3
    consumer:
      auto-offset-reset: latest
  sleuth:
    sampler:
      # ProbabilityBasedSampler 抽样策略
      probability: 1.0  # 采样比例, 1.0 表示 100%, 默认是 0.1
      # RateLimitingSampler 抽样策略, 设置了限速采集, spring.sleuth.sampler.probability 属性值无效
      rate: 100  # 每秒间隔接受的 trace 量
  zipkin:
    sender:
      type: kafka # 默认是 web
    base-url: http://192.168.31.128:9411/
    service:
      name: ${spring.application.name}

  datasource:
    dynamic:
      primary: qingyin-authority-db #设置默认的数据源或者数据源组
      strict: false
      datasource:
        qingyin-authority-db:
          url: jdbc:mysql://localhost:3306/qingyin-authority?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver # MySql的驱动
          username: root # 数据库账号
          password: 123456 # 数据库密码