server:
  port: 8077

spring:

  cloud:
    nacos:
      discovery:
        enabled: true
        username: nacos
        password: nacos
        server-addr: 192.168.31.211:8848
        namespace: qingyin
